apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    environment: test-backup
  labels:
    app: mysql
    environment: test-backup
    version: 8.0.15
  name: mysql-sts
  namespace: test-backup
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mysql
      environment: test-backup
      version: 8.0.15
  serviceName: ""
  template:
    metadata:
      annotations:
        environment: test-backup
      labels:
        app: mysql
        environment: test-backup
        version: 8.0.15
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql:8.0.15
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              cpu: 512m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - chown -R 999:999 /var/lib/mysql; rm -fr /var/lib/mysql/lost+found;
          image: ubuntu:16.04
          imagePullPolicy: IfNotPresent
          name: remove-lost-found
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
